# FLTKGUI is not required for the Qt4,0 gui.
#

all:
	make -C pqi
	make -C	util
	make -C	dbase
	make -C	server
	make -C	dht
	make -C	rsserver
	make -C	rsiface
#	make -C	fltkgui

clean:
	make -C pqi clean
	make -C	util clean
	make -C	dbase clean
	make -C	server clean
	make -C	dht clean
	make -C	rsserver clean
	make -C	rsiface clean
#	make -C	fltkgui clean

clobber:
	make -C pqi clobber
	make -C	util clobber
	make -C	dbase clobber
	make -C	server clobber
	make -C	dht clobber
	make -C	rsserver clobber
	make -C	rsiface clobber
#	make -C	fltkgui clobber

